language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
  - ./scripts/test.sh
  - ./scripts/test-e2e.sh
after_success:
  - ./scripts/travis-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
